#############################################################################
# Makefile for building: OpenGooDts
# Generated by qmake (2.01a) (Qt 4.8.1) on: Tue Jun 12 20:05:56 2012
# Project:  OpenGooDts.pro
# Template: app
# Command: /usr/bin/qmake-qt4 -spec /usr/lib/qt4/mkspecs/linux-g++-32 CONFIG+=debug CONFIG+=declarative_debug -o Makefile OpenGooDts.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_XML_LIB -DQT_GUI_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -m32 -pipe -g -Wall -W -D_REENTRANT $(DEFINES)
CXXFLAGS      = -m32 -pipe -g -Wall -W -D_REENTRANT $(DEFINES)
INCPATH       = -I/usr/lib/qt4/mkspecs/linux-g++-32 -I. -I/usr/include/QtCore -I/usr/include/QtGui -I/usr/include/QtXml -I/usr/include -I. -I.
LINK          = g++
LFLAGS        = -m32
LIBS          = $(SUBLIBS)  -L/usr/lib -lQtXml -lQtGui -lQtCore -lpthread 
AR            = ar cqs
RANLIB        = 
QMAKE         = /usr/bin/qmake-qt4
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
STRIP         = 
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.cpp \
		managergui.cpp \
		wizardgui_s0.cpp \
		wizardgui_s1.cpp \
		wizardgui_s2.cpp \
		wizardgui_s3.cpp \
		wizardmain.cpp \
		tablemodel.cpp \
		viewreport.cpp \
		sendtextreportform.cpp \
		report.cpp \
		architecture.cpp \
		xmlmodule.cpp \
		tablesmodel.cpp moc_managergui.cpp \
		moc_wizardgui_s0.cpp \
		moc_wizardgui_s1.cpp \
		moc_wizardgui_s2.cpp \
		moc_wizardgui_s3.cpp \
		moc_wizardmain.cpp \
		moc_tablemodel.cpp \
		moc_viewreport.cpp \
		moc_sendtextreportform.cpp \
		moc_tablesmodel.cpp \
		qrc_res.cpp
OBJECTS       = main.o \
		managergui.o \
		wizardgui_s0.o \
		wizardgui_s1.o \
		wizardgui_s2.o \
		wizardgui_s3.o \
		wizardmain.o \
		tablemodel.o \
		viewreport.o \
		sendtextreportform.o \
		report.o \
		architecture.o \
		xmlmodule.o \
		tablesmodel.o \
		moc_managergui.o \
		moc_wizardgui_s0.o \
		moc_wizardgui_s1.o \
		moc_wizardgui_s2.o \
		moc_wizardgui_s3.o \
		moc_wizardmain.o \
		moc_tablemodel.o \
		moc_viewreport.o \
		moc_sendtextreportform.o \
		moc_tablesmodel.o \
		qrc_res.o
DIST          = /usr/lib/qt4/mkspecs/common/unix.conf \
		/usr/lib/qt4/mkspecs/common/linux.conf \
		/usr/lib/qt4/mkspecs/common/gcc-base.conf \
		/usr/lib/qt4/mkspecs/common/gcc-base-unix.conf \
		/usr/lib/qt4/mkspecs/common/g++-base.conf \
		/usr/lib/qt4/mkspecs/common/g++-unix.conf \
		/usr/lib/qt4/mkspecs/qconfig.pri \
		/usr/lib/qt4/mkspecs/modules/qt_phonon.pri \
		/usr/lib/qt4/mkspecs/modules/qt_webkit_version.pri \
		/usr/lib/qt4/mkspecs/features/qt_functions.prf \
		/usr/lib/qt4/mkspecs/features/qt_config.prf \
		/usr/lib/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/lib/qt4/mkspecs/features/default_pre.prf \
		/usr/lib/qt4/mkspecs/features/debug.prf \
		/usr/lib/qt4/mkspecs/features/default_post.prf \
		/usr/lib/qt4/mkspecs/features/declarative_debug.prf \
		/usr/lib/qt4/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/lib/qt4/mkspecs/features/warn_on.prf \
		/usr/lib/qt4/mkspecs/features/qt.prf \
		/usr/lib/qt4/mkspecs/features/unix/thread.prf \
		/usr/lib/qt4/mkspecs/features/moc.prf \
		/usr/lib/qt4/mkspecs/features/resources.prf \
		/usr/lib/qt4/mkspecs/features/uic.prf \
		/usr/lib/qt4/mkspecs/features/yacc.prf \
		/usr/lib/qt4/mkspecs/features/lex.prf \
		/usr/lib/qt4/mkspecs/features/include_source_dir.prf \
		OpenGooDts.pro
QMAKE_TARGET  = OpenGooDts
DESTDIR       = 
TARGET        = OpenGooDts

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET): ui_managergui.h ui_wizardgui_s0.h ui_wizardgui_s1.h ui_wizardgui_s2.h ui_wizardgui_s3.h ui_viewreport.h ui_sendtextreportform.h $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)
	{ test -n "$(DESTDIR)" && DESTDIR="$(DESTDIR)" || DESTDIR=.; } && test $$(gdb --version | sed -e 's,[^0-9]\+\([0-9]\)\.\([0-9]\).*,\1\2,;q') -gt 72 && gdb --nx --batch --quiet -ex 'set confirm off' -ex "save gdb-index $$DESTDIR" -ex quit '$(TARGET)' && test -f $(TARGET).gdb-index && objcopy --add-section '.gdb_index=$(TARGET).gdb-index' --set-section-flags '.gdb_index=readonly' '$(TARGET)' '$(TARGET)' && rm -f $(TARGET).gdb-index || true

Makefile: OpenGooDts.pro  /usr/lib/qt4/mkspecs/linux-g++-32/qmake.conf /usr/lib/qt4/mkspecs/common/unix.conf \
		/usr/lib/qt4/mkspecs/common/linux.conf \
		/usr/lib/qt4/mkspecs/common/gcc-base.conf \
		/usr/lib/qt4/mkspecs/common/gcc-base-unix.conf \
		/usr/lib/qt4/mkspecs/common/g++-base.conf \
		/usr/lib/qt4/mkspecs/common/g++-unix.conf \
		/usr/lib/qt4/mkspecs/qconfig.pri \
		/usr/lib/qt4/mkspecs/modules/qt_phonon.pri \
		/usr/lib/qt4/mkspecs/modules/qt_webkit_version.pri \
		/usr/lib/qt4/mkspecs/features/qt_functions.prf \
		/usr/lib/qt4/mkspecs/features/qt_config.prf \
		/usr/lib/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/lib/qt4/mkspecs/features/default_pre.prf \
		/usr/lib/qt4/mkspecs/features/debug.prf \
		/usr/lib/qt4/mkspecs/features/default_post.prf \
		/usr/lib/qt4/mkspecs/features/declarative_debug.prf \
		/usr/lib/qt4/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/lib/qt4/mkspecs/features/warn_on.prf \
		/usr/lib/qt4/mkspecs/features/qt.prf \
		/usr/lib/qt4/mkspecs/features/unix/thread.prf \
		/usr/lib/qt4/mkspecs/features/moc.prf \
		/usr/lib/qt4/mkspecs/features/resources.prf \
		/usr/lib/qt4/mkspecs/features/uic.prf \
		/usr/lib/qt4/mkspecs/features/yacc.prf \
		/usr/lib/qt4/mkspecs/features/lex.prf \
		/usr/lib/qt4/mkspecs/features/include_source_dir.prf \
		/usr/lib/libQtXml.prl \
		/usr/lib/libQtCore.prl \
		/usr/lib/libQtGui.prl
	$(QMAKE) -spec /usr/lib/qt4/mkspecs/linux-g++-32 CONFIG+=debug CONFIG+=declarative_debug -o Makefile OpenGooDts.pro
/usr/lib/qt4/mkspecs/common/unix.conf:
/usr/lib/qt4/mkspecs/common/linux.conf:
/usr/lib/qt4/mkspecs/common/gcc-base.conf:
/usr/lib/qt4/mkspecs/common/gcc-base-unix.conf:
/usr/lib/qt4/mkspecs/common/g++-base.conf:
/usr/lib/qt4/mkspecs/common/g++-unix.conf:
/usr/lib/qt4/mkspecs/qconfig.pri:
/usr/lib/qt4/mkspecs/modules/qt_phonon.pri:
/usr/lib/qt4/mkspecs/modules/qt_webkit_version.pri:
/usr/lib/qt4/mkspecs/features/qt_functions.prf:
/usr/lib/qt4/mkspecs/features/qt_config.prf:
/usr/lib/qt4/mkspecs/features/exclusive_builds.prf:
/usr/lib/qt4/mkspecs/features/default_pre.prf:
/usr/lib/qt4/mkspecs/features/debug.prf:
/usr/lib/qt4/mkspecs/features/default_post.prf:
/usr/lib/qt4/mkspecs/features/declarative_debug.prf:
/usr/lib/qt4/mkspecs/features/unix/gdb_dwarf_index.prf:
/usr/lib/qt4/mkspecs/features/warn_on.prf:
/usr/lib/qt4/mkspecs/features/qt.prf:
/usr/lib/qt4/mkspecs/features/unix/thread.prf:
/usr/lib/qt4/mkspecs/features/moc.prf:
/usr/lib/qt4/mkspecs/features/resources.prf:
/usr/lib/qt4/mkspecs/features/uic.prf:
/usr/lib/qt4/mkspecs/features/yacc.prf:
/usr/lib/qt4/mkspecs/features/lex.prf:
/usr/lib/qt4/mkspecs/features/include_source_dir.prf:
/usr/lib/libQtXml.prl:
/usr/lib/libQtCore.prl:
/usr/lib/libQtGui.prl:
qmake:  FORCE
	@$(QMAKE) -spec /usr/lib/qt4/mkspecs/linux-g++-32 CONFIG+=debug CONFIG+=declarative_debug -o Makefile OpenGooDts.pro

dist: 
	@$(CHK_DIR_EXISTS) .tmp/OpenGooDts1.0.0 || $(MKDIR) .tmp/OpenGooDts1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/OpenGooDts1.0.0/ && $(COPY_FILE) --parents managergui.h wizardgui_s0.h wizardgui_s1.h wizardgui_s2.h wizardgui_s3.h wizardmain.h tablemodel.h viewreport.h sendtextreportform.h report.h architecture.h xmlmodule.h tablesmodel.h .tmp/OpenGooDts1.0.0/ && $(COPY_FILE) --parents res.qrc .tmp/OpenGooDts1.0.0/ && $(COPY_FILE) --parents main.cpp managergui.cpp wizardgui_s0.cpp wizardgui_s1.cpp wizardgui_s2.cpp wizardgui_s3.cpp wizardmain.cpp tablemodel.cpp viewreport.cpp sendtextreportform.cpp report.cpp architecture.cpp xmlmodule.cpp tablesmodel.cpp .tmp/OpenGooDts1.0.0/ && $(COPY_FILE) --parents managergui.ui wizardgui_s0.ui wizardgui_s1.ui wizardgui_s2.ui wizardgui_s3.ui viewreport.ui sendtextreportform.ui .tmp/OpenGooDts1.0.0/ && (cd `dirname .tmp/OpenGooDts1.0.0` && $(TAR) OpenGooDts1.0.0.tar OpenGooDts1.0.0 && $(COMPRESS) OpenGooDts1.0.0.tar) && $(MOVE) `dirname .tmp/OpenGooDts1.0.0`/OpenGooDts1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/OpenGooDts1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


check: first

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all: moc_managergui.cpp moc_wizardgui_s0.cpp moc_wizardgui_s1.cpp moc_wizardgui_s2.cpp moc_wizardgui_s3.cpp moc_wizardmain.cpp moc_tablemodel.cpp moc_viewreport.cpp moc_sendtextreportform.cpp moc_tablesmodel.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_managergui.cpp moc_wizardgui_s0.cpp moc_wizardgui_s1.cpp moc_wizardgui_s2.cpp moc_wizardgui_s3.cpp moc_wizardmain.cpp moc_tablemodel.cpp moc_viewreport.cpp moc_sendtextreportform.cpp moc_tablesmodel.cpp
moc_managergui.cpp: sendtextreportform.h \
		report.h \
		architecture.h \
		wizardmain.h \
		wizardgui_s0.h \
		wizardgui_s1.h \
		wizardgui_s2.h \
		wizardgui_s3.h \
		managergui.h
	/usr/lib/qt4/bin/moc $(DEFINES) $(INCPATH) managergui.h -o moc_managergui.cpp

moc_wizardgui_s0.cpp: wizardgui_s0.h
	/usr/lib/qt4/bin/moc $(DEFINES) $(INCPATH) wizardgui_s0.h -o moc_wizardgui_s0.cpp

moc_wizardgui_s1.cpp: wizardgui_s1.h
	/usr/lib/qt4/bin/moc $(DEFINES) $(INCPATH) wizardgui_s1.h -o moc_wizardgui_s1.cpp

moc_wizardgui_s2.cpp: wizardgui_s2.h
	/usr/lib/qt4/bin/moc $(DEFINES) $(INCPATH) wizardgui_s2.h -o moc_wizardgui_s2.cpp

moc_wizardgui_s3.cpp: wizardgui_s3.h
	/usr/lib/qt4/bin/moc $(DEFINES) $(INCPATH) wizardgui_s3.h -o moc_wizardgui_s3.cpp

moc_wizardmain.cpp: wizardgui_s0.h \
		wizardgui_s1.h \
		wizardgui_s2.h \
		wizardgui_s3.h \
		report.h \
		architecture.h \
		wizardmain.h
	/usr/lib/qt4/bin/moc $(DEFINES) $(INCPATH) wizardmain.h -o moc_wizardmain.cpp

moc_tablemodel.cpp: tablemodel.h
	/usr/lib/qt4/bin/moc $(DEFINES) $(INCPATH) tablemodel.h -o moc_tablemodel.cpp

moc_viewreport.cpp: viewreport.h
	/usr/lib/qt4/bin/moc $(DEFINES) $(INCPATH) viewreport.h -o moc_viewreport.cpp

moc_sendtextreportform.cpp: sendtextreportform.h
	/usr/lib/qt4/bin/moc $(DEFINES) $(INCPATH) sendtextreportform.h -o moc_sendtextreportform.cpp

moc_tablesmodel.cpp: report.h \
		architecture.h \
		tablesmodel.h
	/usr/lib/qt4/bin/moc $(DEFINES) $(INCPATH) tablesmodel.h -o moc_tablesmodel.cpp

compiler_rcc_make_all: qrc_res.cpp
compiler_rcc_clean:
	-$(DEL_FILE) qrc_res.cpp
qrc_res.cpp: res.qrc \
		res/g4567.png \
		res/black-goo.v1.0.svg \
		res/logo.svg \
		res/black-goo.riscaled.png \
		res/icon.png
	/usr/lib/qt4/bin/rcc -name res res.qrc -o qrc_res.cpp

compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: ui_managergui.h ui_wizardgui_s0.h ui_wizardgui_s1.h ui_wizardgui_s2.h ui_wizardgui_s3.h ui_viewreport.h ui_sendtextreportform.h
compiler_uic_clean:
	-$(DEL_FILE) ui_managergui.h ui_wizardgui_s0.h ui_wizardgui_s1.h ui_wizardgui_s2.h ui_wizardgui_s3.h ui_viewreport.h ui_sendtextreportform.h
ui_managergui.h: managergui.ui
	/usr/lib/qt4/bin/uic managergui.ui -o ui_managergui.h

ui_wizardgui_s0.h: wizardgui_s0.ui
	/usr/lib/qt4/bin/uic wizardgui_s0.ui -o ui_wizardgui_s0.h

ui_wizardgui_s1.h: wizardgui_s1.ui
	/usr/lib/qt4/bin/uic wizardgui_s1.ui -o ui_wizardgui_s1.h

ui_wizardgui_s2.h: wizardgui_s2.ui
	/usr/lib/qt4/bin/uic wizardgui_s2.ui -o ui_wizardgui_s2.h

ui_wizardgui_s3.h: wizardgui_s3.ui
	/usr/lib/qt4/bin/uic wizardgui_s3.ui -o ui_wizardgui_s3.h

ui_viewreport.h: viewreport.ui
	/usr/lib/qt4/bin/uic viewreport.ui -o ui_viewreport.h

ui_sendtextreportform.h: sendtextreportform.ui
	/usr/lib/qt4/bin/uic sendtextreportform.ui -o ui_sendtextreportform.h

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean compiler_rcc_clean compiler_uic_clean 

####### Compile

main.o: main.cpp managergui.h \
		sendtextreportform.h \
		report.h \
		architecture.h \
		wizardmain.h \
		wizardgui_s0.h \
		wizardgui_s1.h \
		wizardgui_s2.h \
		wizardgui_s3.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

managergui.o: managergui.cpp managergui.h \
		sendtextreportform.h \
		report.h \
		architecture.h \
		wizardmain.h \
		wizardgui_s0.h \
		wizardgui_s1.h \
		wizardgui_s2.h \
		wizardgui_s3.h \
		ui_managergui.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o managergui.o managergui.cpp

wizardgui_s0.o: wizardgui_s0.cpp wizardgui_s0.h \
		ui_wizardgui_s0.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o wizardgui_s0.o wizardgui_s0.cpp

wizardgui_s1.o: wizardgui_s1.cpp wizardgui_s1.h \
		ui_wizardgui_s1.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o wizardgui_s1.o wizardgui_s1.cpp

wizardgui_s2.o: wizardgui_s2.cpp wizardgui_s2.h \
		ui_wizardgui_s2.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o wizardgui_s2.o wizardgui_s2.cpp

wizardgui_s3.o: wizardgui_s3.cpp wizardgui_s3.h \
		ui_wizardgui_s3.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o wizardgui_s3.o wizardgui_s3.cpp

wizardmain.o: wizardmain.cpp wizardmain.h \
		wizardgui_s0.h \
		wizardgui_s1.h \
		wizardgui_s2.h \
		wizardgui_s3.h \
		report.h \
		architecture.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o wizardmain.o wizardmain.cpp

tablemodel.o: tablemodel.cpp tablemodel.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o tablemodel.o tablemodel.cpp

viewreport.o: viewreport.cpp viewreport.h \
		ui_viewreport.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o viewreport.o viewreport.cpp

sendtextreportform.o: sendtextreportform.cpp sendtextreportform.h \
		ui_sendtextreportform.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o sendtextreportform.o sendtextreportform.cpp

report.o: report.cpp report.h \
		architecture.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o report.o report.cpp

architecture.o: architecture.cpp architecture.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o architecture.o architecture.cpp

xmlmodule.o: xmlmodule.cpp xmlmodule.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o xmlmodule.o xmlmodule.cpp

tablesmodel.o: tablesmodel.cpp tablesmodel.h \
		report.h \
		architecture.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o tablesmodel.o tablesmodel.cpp

moc_managergui.o: moc_managergui.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_managergui.o moc_managergui.cpp

moc_wizardgui_s0.o: moc_wizardgui_s0.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_wizardgui_s0.o moc_wizardgui_s0.cpp

moc_wizardgui_s1.o: moc_wizardgui_s1.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_wizardgui_s1.o moc_wizardgui_s1.cpp

moc_wizardgui_s2.o: moc_wizardgui_s2.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_wizardgui_s2.o moc_wizardgui_s2.cpp

moc_wizardgui_s3.o: moc_wizardgui_s3.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_wizardgui_s3.o moc_wizardgui_s3.cpp

moc_wizardmain.o: moc_wizardmain.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_wizardmain.o moc_wizardmain.cpp

moc_tablemodel.o: moc_tablemodel.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_tablemodel.o moc_tablemodel.cpp

moc_viewreport.o: moc_viewreport.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_viewreport.o moc_viewreport.cpp

moc_sendtextreportform.o: moc_sendtextreportform.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_sendtextreportform.o moc_sendtextreportform.cpp

moc_tablesmodel.o: moc_tablesmodel.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_tablesmodel.o moc_tablesmodel.cpp

qrc_res.o: qrc_res.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qrc_res.o qrc_res.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

